services:
  php:
    container_name: symfony_php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
    user: "${UID}"

  mysql:
    container_name: symfony_mysql
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    user: "${UID}"
